{{- if (ne .Values.storage.driver "InMemory") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "miniurl.storageSecretName" . }}
type: Opaque
{{- if eq .Values.storage.driver "Postgres" }}
{{- if not .Values.storage.deploy }}
stringData: 
  password: {{ required "storage.postgresConfig.secrets.password is required if the storage.driver is set to 'Postgres' and storage.deploy is set to false" .Values.storage.postgresConfig.secrets.password }}
{{- else }} # storage.deploy = true
data:
{{- if .Release.IsUpgrade }}
  postgresql-password:  {{ index (lookup "v1" "Secret" .Release.Namespace (tpl .Values.postgresql.existingSecret .)).data "postgresql-password" }}
{{- else }} # install operation
  postgresql-password: {{ randAlphaNum 20 | b64enc }} 
{{- end }}
{{- end }}
{{- end }}
{{- end }}
