apiVersion: v1
kind: Secret
metadata:
  name: {{ include "miniurl.storageSecretName" . }}
type: Opaque
stringData:
{{ if eq .Values.storage.driver "Postgres" }}
{{ if and (not .Values.storage.deploy) (ne .Values.storage.driver "InMemory") }}
  password: {{ required "storage.postgresConfig.secrets.password is required if the storage.driver is set to 'Postgres' and storage.deploy is set to false" }}
{{ end }}
data:
  postgresql-password: {{ randAlphaNum 20 | b64enc }}
{{ end }}