{{ if and (not .Values.storage.deploy) (ne .Values.storage.driver "InMemory") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "miniurl.storageSecretName" . }}
type: Opaque
stringData:
{{ if eq .Values.storage.driver "Relational" }}
  password: {{ required "storage.relationalConfig.secrets.password is required if the storage.driver is set to 'Relational' and storage.deploy is set to false" }}
{{ end }}
{{ end }}
